[package]
name = "iosevka-template"
version = "0.2.0"
authors = ["Iku Iwasa <iku.iwasa@gmail.com>"]
edition = "2024"

[dependencies]
handlebars = { version = "6.0.0", features = ["string_helpers"] }
toml = "0.9.5"
serde = { version = "1.0.126", features = ["derive"] }
