[package]
name = "iosevka-template"
version = "0.2.0"
authors = ["Iku Iwasa <iku.iwasa@gmail.com>"]
edition = "2018"

[dependencies]
handlebars = "4.1.0"
toml = "0.5.8"
serde = { version = "1.0.126", features = ["derive"] }
