[package]
name = "iosevka-template"
version = "0.1.0"
authors = ["Iku Iwasa <iku.iwasa@gmail.com>"]
edition = "2018"

[dependencies]
handlebars = "^1.1.0"
toml = "^0.5.0"
serde = { version = "^1.0.89", features = ["derive"] }
